import numpy as np
import pandas as pd
from hmmlearn import hmm
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split


class WyckoffMarkovModel:
    def __init__(self, n_states=4, patience=10):
        """
        Initialize the Wyckoff Markov model with a specified number of states and early stopping patience.
        """
        self.n_states = n_states
        self.patience = patience
        self.model = hmm.GaussianHMM(n_components=n_states, 
                                     #covariance_type="diag", 
                                     n_iter=100)

    def train(self, train_data, val_data):
        """
        Train the Markov model with early stopping.
        """
        train_data = train_data.reshape(-1, 1)
        val_data = val_data.reshape(-1, 1)

        best_val_loss = float('inf')
        no_improvement_count = 0

        for iteration in range(100):  # Maximum training iterations
            if iteration == 0:
                # Initialize the model parameters in the first iteration
                self.model.fit(train_data)
            else:
                # Do not re-initialize the model parameters in subsequent iterations
                self.model.init_params = ''
                self.model.fit(train_data)

            val_states = self.model.predict(val_data)
            val_reconstructed = self.model.means_[val_states].flatten()
            val_loss = mean_squared_error(val_data, val_reconstructed)

            print(f"Iteration {iteration}, Validation Loss: {val_loss:.6f}")

            if val_loss < best_val_loss:
                best_val_loss = val_loss
                no_improvement_count = 0
            else:
                no_improvement_count += 1

            if no_improvement_count >= self.patience:
                print(f"Early stopping at iteration {iteration}. Best validation loss: {best_val_loss:.6f}")
                break

    def predict_states(self, data):
        """
        Predict the states of the historical data.
        """
        data = data.reshape(-1, 1)
        return self.model.predict(data)

    def project_future(self, steps):
        """
        Generate future predictions based on the Markov model.
        """
        future_samples, _ = self.model.sample(steps)
        return future_samples.flatten()

    def evaluate_model(self, data, true_states=None):
        """
        Evaluate the model using historical data.
        """
        data = data.reshape(-1, 1)
        predicted_states = self.model.predict(data)

        results = {}

        # Reconstruction error (using mean absolute error)
        reconstructed_data = self.model.means_[predicted_states].flatten()
        results["Reconstruction MAE"] = mean_absolute_error(data, reconstructed_data)
        results["Reconstruction RMSE"] = np.sqrt(mean_squared_error(data, reconstructed_data))

        return results


def load_and_preprocess_data(filepath, target_column="output"):
    """
    Load and preprocess the stock price data.
    """
    # Load the dataset
    df = pd.read_csv(filepath)
    target_data = df['SeqClose'] + df['output']
    data = df[['output']].values

    # Normalize the data
    normalized_data = (data - np.mean(data)) / np.std(data)
    return normalized_data.flatten(), data.flatten(), target_data.values


def plot_stock_with_cycles(original_data, historical_states, projections, show_projections=10, last_x=None):
    """
    Plot the stock price with annotated Wyckoff cycles and projections.

    Parameters:
    - original_data: The stock price data.
    - historical_states: The predicted states corresponding to the data.
    - projections: Future projections generated by the model.
    - show_projections: Number of future projections to display.
    - last_x: Plot only the last 'x' data points if specified.
    """
    if last_x is not None:
        # Ensure last_x does not exceed the length of original_data
        last_x = min(last_x, len(original_data))
        original_data = original_data[-last_x:]
        historical_states = historical_states[-last_x:]
        time_axis = np.arange(len(original_data))
    else:
        time_axis = np.arange(len(original_data))

    plt.figure(figsize=(14, 7))

    # Plot historical stock data
    plt.plot(time_axis, original_data, label="Historical Prices", color="black")

    # Annotate Wyckoff cycles
    colors = ["green", "orange", "red", "purple"]
    unique_states = np.unique(historical_states)
    for state in unique_states:
        idx = (historical_states == state)
        plt.scatter(
            time_axis[idx],
            original_data[idx],
            label=f"State {state + 1}",
            color=colors[state % len(colors)],
            s=75,
        )

    # Add future projections
    if projections is not None and show_projections > 0:
        projection_range = np.arange(time_axis[-1] + 1, time_axis[-1] + 1 + show_projections)
        plt.plot(
            projection_range,
            projections[:show_projections],
            label="Projections",
            color="black",
            linestyle="dashed",
        )

    plt.xlabel("Time")
    plt.ylabel("Stock Price")
    plt.legend()
    plt.title("Stock Price Movements with Wyckoff Cycles")
    plt.show()


def main():
    # Load and preprocess the data
    file_path = 'data/NewModel_3070_oos.csv'
    normalized_data, original_data, target_data = load_and_preprocess_data(file_path)

    # Split data into train, validation, and test sets
    train_data, temp_data = train_test_split(normalized_data, test_size=0.3, random_state=42)
    val_data, test_data = train_test_split(temp_data, test_size=0.5, random_state=42)

    # Initialize and train the Markov model
    wyckoff_model = WyckoffMarkovModel()
    wyckoff_model.train(train_data, val_data)

    # Predict historical states
    historical_states = wyckoff_model.predict_states(normalized_data)

    # Project future stock prices
    steps = 30  # Number of steps to project
    future_projections = wyckoff_model.project_future(steps)

    future_projections = None

    # Evaluate the model
    test_results = wyckoff_model.evaluate_model(test_data)
    print("\nTest Set Evaluation Results:")
    for metric, value in test_results.items():
        print(f"{metric}: {value:.6f}")

    # Visualize the results
    x = 10000  # Number of last items to plot
    plot_stock_with_cycles(
        target_data,
        historical_states,
        future_projections,
        show_projections=10,
        last_x=x
    )


if __name__ == "__main__":
    main()
